version: '2'

services:
  calibre_tools:
    image: brutus/calibre
    container_name: calibre_tools
    hostname: calibre_tools
    restart: always
    environment:
      TZ: Europe/Berlin
      PUID: $UID
      PGID: $GID
    volumes:
      - "~/Projects/HomeWork/Docker/calibre4news/docker/target:/target:rw"
#      - "~/Projects/HomeWork/Docker/calibre4news/data/target:/target:rw"
      - "~/Projects/HomeWork/Docker/calibre4news/data/config:/config:rw"
